[package]
name = "sphynx_core"
version = "0.1.0"
edition = "2021"

[dependencies]
sphynx_logging = { path = "../logging" }
sphynx_input = { path = "../input" }
sphynx_rendering = { path = "../rendering" }
anyhow = { workspace = true }
winit = { workspace = true }
cgmath = { workspace = true }