name: C++ Windows VS2022 Build
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Generate VS2022 Solution
        run: BuildProjectWin.bat
        working-directory: Scripts

      - name: Setup VS2022
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64
        
      - name: Build Debug Solution
        run: msbuild /p:Configurations=Debug /p:Platform=x64 /m /p:WarningLevel=4 SphynxEngine.sln
      - name: Build Release Solution
        run: msbuild /p:Configurations=Release /p:Platform=x64 /m /p:WarningLevel=4 SphynxEngine.sln
      - name: Build Dist Solution
        run: msbuild /p:Configurations=Dist /p:Platform=x64 /m /p:WarningLevel=4 SphynxEngine.sln