name: Windows Build
on:
  push:
    paths-ignore:
      - 'TestProject'
      - 'README.md'
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Clone submodules
        run: git submodule update --init --recursive

      - name: Generate VS2022 Solution
        working-directory: Scripts
        run: cmd /C BuildProjectWin.bat

      - name: Setup VS2022
        uses: microsoft/setup-msbuild@v1.3.1
        with:
          msbuild-architecture: x64
        
      - name: Build Debug Solution
        run: msbuild /p:Configurations=Debug /p:Platform=x64 /m /p:WarningLevel=4 SphynxEngine.sln
      - name: Build Release Solution
        run: msbuild /p:Configurations=Release /p:Platform=x64 /m /p:WarningLevel=4 SphynxEngine.sln
      - name: Build Dist Solution
        run: msbuild /p:Configurations=Dist /p:Platform=x64 /m /p:WarningLevel=4 SphynxEngine.sln
  test:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Run Test
        run: bin/windows-x86_64/Release/Programs/Tests/Tests.exe